// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqnnneocoqzobdvyghma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxbm5uZW9jb3F6b2JkdnlnaG1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTE4OTAsImV4cCI6MjA2ODQ2Nzg5MH0.l7_A_3TtNtbSsdQeL88tFnS9GC_UrUKqoA_0smf4NgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});